### ISSUE TITLE
Failing pip install

### ISSUE THREAD

**Issue by MartinHjelmare** [titilambert/pyhydroquebec#12]
Hi!

This package is failing during pip install in home assistant Travis builds. The error message says that there's no module named `pip.req`, which `setup.py` is relying on.

https://travis-ci.org/home-assistant/home-assistant/jobs/367048309

This could possibly be related to pip releasing 10.0. I haven't reproduced this locally yet. I'll try to do that soon.

Edit:
Ok, I've reproduced the error locally in a fresh venv with pip 10.0.0:
```
(pyhydroquebec) martin@martin-ThinkPad-T460s:~$ pip install pyhydroquebec
Collecting pyhydroquebec
  Downloading pyhydroquebec-2.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xl9rezok/pyhydroquebec/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xl9rezok/pyhydroquebec/
```

Downgrading to pip 9.0.3 successfully installs this package:
```
(pyhydroquebec) martin@martin-ThinkPad-T460s:~$ pip install "pip<10.0"
Collecting pip<10.0
  Using cached pip-9.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.0
    Uninstalling pip-10.0.0:
      Successfully uninstalled pip-10.0.0
Successfully installed pip-9.0.3
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pyhydroquebec) martin@martin-ThinkPad-T460s:~$ pip install pyhydroquebec
Collecting pyhydroquebec
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading pyhydroquebec-2.2.1.tar.gz
Collecting aiohttp (from pyhydroquebec)
  Downloading aiohttp-3.1.3-cp36-cp36m-manylinux1_x86_64.whl (661kB)
    100% |████████████████████████████████| 665kB 882kB/s 
Collecting bs4 (from pyhydroquebec)
  Downloading bs4-0.0.1.tar.gz
Collecting async-timeout<3.0,>=1.2 (from aiohttp->pyhydroquebec)
  Using cached async_timeout-2.0.1-py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp->pyhydroquebec)
  Downloading multidict-4.2.0-cp36-cp36m-manylinux1_x86_64.whl (473kB)
    100% |████████████████████████████████| 481kB 1.0MB/s 
Collecting chardet<4.0,>=2.0 (from aiohttp->pyhydroquebec)
  Cache entry deserialization failed, entry ignored
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna-ssl>=1.0 (from aiohttp->pyhydroquebec)
  Downloading idna-ssl-1.0.1.tar.gz
Collecting attrs>=17.3.0 (from aiohttp->pyhydroquebec)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp->pyhydroquebec)
  Downloading yarl-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (255kB)
    100% |████████████████████████████████| 256kB 1.1MB/s 
Collecting beautifulsoup4 (from bs4->pyhydroquebec)
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl
Collecting idna>=2.0 (from idna-ssl>=1.0->aiohttp->pyhydroquebec)
  Cache entry deserialization failed, entry ignored
  Using cached idna-2.6-py2.py3-none-any.whl
Building wheels for collected packages: pyhydroquebec, bs4, idna-ssl
  Running setup.py bdist_wheel for pyhydroquebec ... done
  Stored in directory: /home/martin/.cache/pip/wheels/95/b8/e3/2bf5cc801f005e18ff7fd664f61238e99376e246b5739d02bf
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /home/martin/.cache/pip/wheels/84/67/d4/9e09d9d5adede2ee1c7b7e8775ba3fbb04d07c4f946f0e4f11
  Running setup.py bdist_wheel for idna-ssl ... done
  Stored in directory: /home/martin/.cache/pip/wheels/b8/01/3c/37f9f2ab95297ba796465c4094345eb22f247df1a9096ad0ba
Successfully built pyhydroquebec bs4 idna-ssl
Installing collected packages: async-timeout, multidict, chardet, idna, idna-ssl, attrs, yarl, aiohttp, beautifulsoup4, bs4, pyhydroquebec
Successfully installed aiohttp-3.1.3 async-timeout-2.0.1 attrs-17.4.0 beautifulsoup4-4.6.0 bs4-0.0.1 chardet-3.0.4 idna-2.6 idna-ssl-1.0.1 multidict-4.2.0 pyhydroquebec-2.2.1 yarl-1.1.1
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by djfjeff** [comment]
Can confirm here, the component stop working since the upgrade to HASS 0.67 this morning (which updated pip to 10 also). Same error as above.

**Comment by titilambert** [comment]
HomeAssistant PR: https://github.com/home-assistant/home-assistant/pull/13946
