### ISSUE TITLE
'HQ_TIMEZONE' error

### ISSUE THREAD

**Issue by arnaud-42** [titilambert/pyhydroquebec#18]
I don't know what to do with this error message ...

Traceback (most recent call last):
  File "/home/arnaud/.local/bin/pyhydroquebec", line 11, in <module>
    load_entry_point('pyhydroquebec', 'console_scripts', 'pyhydroquebec')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/arnaud/dev/pyhydroquebec13juin2018/pyhydroquebec/pyhydroquebec/__main__.py", line 8, in <module>
    from pyhydroquebec import HydroQuebecClient, REQUESTS_TIMEOUT, HQ_TIMEZONE
ImportError: cannot import name 'HQ_TIMEZONE'

**Comment by kevmegforest** [comment]
I've made the fix on my branch

**Comment by titilambert** [comment]
#19 merged fixes this issue
