### ISSUE TITLE
Hydro-Québec sensor fails to init with unexpected mimetype error

### ISSUE THREAD

**Issue by ParitoshBh** [titilambert/pyhydroquebec#23]
**Home Assistant release with the issue:** 0.75.3

**Operating environment (Hass.io/Docker/Windows/etc.):** Docker (running in Ubuntu 18.04 virtual machine)

**Description of problem:**
Sensor fails to initialize with following error,

```python
2018-08-11 22:16:19 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hydroquebec
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/src/app/homeassistant/components/sensor/hydroquebec.py", line 109, in async_setup_platform
    contracts = yield from hydroquebec_data.get_contract_list()
  File "/usr/src/app/homeassistant/components/sensor/hydroquebec.py", line 180, in get_contract_list
    ret = yield from self._fetch_data()
  File "/usr/src/app/homeassistant/components/sensor/hydroquebec.py", line 190, in _fetch_data
    await self.client.fetch_data()
  File "/usr/local/lib/python3.6/site-packages/pyhydroquebec/client.py", line 372, in fetch_data
    hourly_data = yield from self._get_hourly_data(day_date, p_p_id)
  File "/usr/local/lib/python3.6/site-packages/pyhydroquebec/client.py", line 309, in _get_hourly_data
    json_output = yield from raw_res.json(content_type='text/json')
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 927, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
```

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
sensor:
  - platform: transmission
    host: INTERNAL_IP
    username: transmission
    password: transmission
    monitored_variables:
      #- 'current_status'
      - 'download_speed'
      - 'active_torrents'
      #- 'paused_torrents'
  - platform: hydroquebec
    username: USERNAME
    password: PASSWORD
    contract: CONTRACTNO
    monitored_variables:
#     - period_total_bill
      - period_total_consumption
#     - period_average_temperature
```

_P.S - Duplicate of https://github.com/home-assistant/home-assistant/issues/15944_

**Comment by titilambert** [comment]
@ParitoshBh @b0ne 
Did you try to run the command manually ? 
```
pyhydroquebec -u USERNAME -p PASSWORD -c ACCOUNT
```

**Comment by titilambert** [comment]
@b0ne Thans s!
This issue comes from, at least, one of this data:
- annual_total_bill
- annual_mean_daily_bill
- annual_total_consumption
- annual_mean_daily_consumption
- annual_kwh_price_cent

Could you rerun the same command with the `-j` option and see what are the values for these data ?

Thanks
BTW: Do you have your HydroQuebec Contract for more than one year ?

**Comment by titilambert** [comment]
This is strange I think we have 2 different issue :/
Could you also rerun an other time the command with `-H` without the `-j`

Thanks !

**Comment by titilambert** [comment]
Ok ! So that's why the annual data are not here !
Perfect I'm fixing now !
Thanls

**Comment by titilambert** [comment]
It seems it's already fixed ! Could you upgrade your repository ?
``` git pull origin master```
then rerun the command

**Comment by titilambert** [comment]
@b0ne  But this bug is not related to the one opened by @ParitoshBh :/
I think this bug if fixed.
@ParitoshBh do you still have the issue ?
If yes maybe we just have to update the Pyhydroquebec version in HomeAssistant

**Comment by ParitoshBh** [comment]
@titilambert Sorry, I am travelling as of now. I can't follow up on your instructions but my account is indeed less than a year old. What would you like me to do? Give it another try with with hass 0.83.2 (upgraded since opening this issue)?

**Comment by b0ne** [comment]
The uodate dosnt fix it. I will try the new pyhydro on my setup dans see if it change something

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by b0ne** [comment]
@titilambert  could you ma a release so I can test it on home assistant. I can't test a newer version than 2.3.0, because the new version 2.4.0 is not available via pip install and the last release on github is 2.2.2

Tks

**Comment by titilambert** [comment]
oki ! So I'm releasing it tonight !

**Comment by ParitoshBh** [comment]
Cloned the repo (with https://github.com/titilambert/pyhydroquebec/commit/4ea1374a63944413889c147d91961eda0605d4fd as last commit). Ran the following tests,

1. With `-H` and `-j` options (no error)

   ![image](https://user-images.githubusercontent.com/11397869/49387723-90662f80-f6f0-11e8-97a0-68f6e0189880.png)

1. With `-H` option (error)

   ![image](https://user-images.githubusercontent.com/11397869/49387819-c5728200-f6f0-11e8-86cb-b642ee0f40f8.png)

**Comment by titilambert** [comment]
@b0ne Version 2.4.0 released on Pypi ! You can now test it !

**Comment by b0ne** [comment]
@titilambert Tks but I will not be able to test it without the fix to the issue #29

**Comment by richarddubois** [comment]
Hi all

thanks @titilambert for working on this. I had the same issue as reported by @ParitoshBh on my HA and I've tested the latest version of pyhydroquebec.

I did updated it, i'm not sure if I did the proper thing... here is my steps:

I did log on into the my docker container
```bash
sudo docker exec -i -t home-assistant /bin/bash
```
Performed then upgrade like this:
```bash
pip install pyhydroquebec==2.4.0 --target /config/deps
```

after that, I did restarted the container and it looks like it tooks the latest pyhydroquebec version but it still failling:
```log
Tue Dec 04 2018 19:31:31 GMT-0500 (UTC−05:00)

Error while setting up platform hydroquebec
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/hydroquebec.py", line 108, in async_setup_platform
    contracts = await hydroquebec_data.get_contract_list()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/hydroquebec.py", line 177, in get_contract_list
    ret = await self._fetch_data()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/hydroquebec.py", line 187, in _fetch_data
    await self.client.fetch_data()
  File "/config/deps/lib/python3.6/site-packages/pyhydroquebec/client.py", line 372, in fetch_data
    hourly_data = yield from self._get_hourly_data(day_date, p_p_id)
  File "/config/deps/lib/python3.6/site-packages/pyhydroquebec/client.py", line 309, in _get_hourly_data
    json_output = yield from raw_res.json(content_type='text/json')
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
```
Any tips?

**Comment by b0ne** [comment]
You are almost there you have to tell home assistant to use pyhydroquebec version 2.4.0. In Hydroquebec.py. 
You got two choice, edit the file at /usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/hydroquebec.py 

or copy the file in the config/custom_components/sensor/hydroquebec.py

See here : https://developers.home-assistant.io/docs/en/creating_component_loading.html

The line you have to edit is the line 21 : REQUIREMENTS = ['pyhydroquebec==2.4.0']

**Comment by b0ne** [comment]
@richarddubois  can you confirm if its working 

@ParitoshBh  can you try it and tell us if its working

For me version 2.4 is working on my home assistant. (When I got Temp data so I don't get the error #29 )

**Comment by richarddubois** [comment]
@b0ne , I confirm it works like a charm! thank you for the missing step

**Comment by ParitoshBh** [comment]
> 
> 
> You are almost there you have to tell home assistant to use pyhydroquebec version 2.4.0. In Hydroquebec.py.
> You got two choice, edit the file at /usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/hydroquebec.py
> 
> or copy the file in the config/custom_components/sensor/hydroquebec.py
> 
> See here : https://developers.home-assistant.io/docs/en/creating_component_loading.html
> 
> The line you have to edit is the line 21 : REQUIREMENTS = ['pyhydroquebec==2.4.0']

Tried last night. Works just fine! Appreciate the help :)

**Comment by b0ne** [comment]
@titilambert I think you can close this ticket, push the update to homeassistant and close the ticket on the homeassistant side 

https://github.com/home-assistant/home-assistant/issues/15944

**Comment by CygaLV** [comment]
Hi !
I've followed the instructions but still experiencing this:
`2018-12-23 17:54:20 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform hydroquebec is taking over 10 seconds.
2018-12-23 17:54:20 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform hydroquebec
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/python3/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
    return fut.result()
  File "/usr/local/python3/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/local/python3/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/local/python3/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 109, in async_setup_platform
    contracts = yield from hydroquebec_data.get_contract_list()
  File "/usr/local/python3/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 180, in get_contract_list
    ret = yield from self._fetch_data()
  File "/usr/local/python3/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 190, in _fetch_data
    await self.client.fetch_data()
  File "/volume1/homeassistant/deps/lib/python3.5/site-packages/pyhydroquebec/client.py", line 372, in fetch_data
    hourly_data = yield from self._get_hourly_data(day_date, p_p_id)
  File "/volume1/homeassistant/deps/lib/python3.5/site-packages/pyhydroquebec/client.py", line 309, in _get_hourly_data
    json_output = yield from raw_res.json(content_type='text/json')
  File "/usr/local/python3/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 927, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'`

I'm on a Synology platform, with HASS 0.75.3 and Python 3.5.8.
I've changed the sensor/hydroquebec.py file to force reading the 2.4.0 version of pyhydroquebec (I've tried writting 2.5.0 to see if had effect on the execution, and indeed I've gor an error saying that 2.5.0 doesn't exits. So my 2.4.0 modification is well read).

On Synology I do not know how to run the pyhydroquebec code with the -H and -J options.
Can you help me here ?

**Comment by titilambert** [comment]
I'm closing this issue because of the Hydroquebec update see https://github.com/titilambert/pyhydroquebec/issues/35
