### ISSUE TITLE
Error while setting up platform hydroquebec

### ISSUE THREAD

**Issue by QcVictor** [titilambert/pyhydroquebec#24]
Hi Guys
Since 2 September I'm unable to get data from hydroquebec, when I swap for my father account
he works ......
When I put my information (single account) this is the ouput from hass:
`Error while setting up platform hydroquebec

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/src/app/homeassistant/components/sensor/hydroquebec.py", line 110, in async_setup_platform
    contracts = yield from hydroquebec_data.get_contract_list()
  File "/usr/src/app/homeassistant/components/sensor/hydroquebec.py", line 181, in get_contract_list
    ret = yield from self._fetch_data()
  File "/usr/src/app/homeassistant/components/sensor/hydroquebec.py", line 191, in _fetch_data
    await self.client.fetch_data()
  File "/usr/local/lib/python3.6/site-packages/pyhydroquebec/client.py", line 387, in fetch_data
    daily_data = yield from self._get_daily_data(p_p_id, start_date, end_date)
  File "/usr/local/lib/python3.6/site-packages/pyhydroquebec/client.py", line 276, in _get_daily_data
    timeout=self._timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 361, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 207, in __init__
    url2 = url.with_query(params)
  File "/usr/local/lib/python3.6/site-packages/yarl/__init__.py", line 857, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/yarl/__init__.py", line 825, in _get_str_query
    "should be str or int, got {!r}".format(v))
TypeError: Invalid variable type: mapping value should be str or int, got None
`

**Comment by QcVictor** [comment]
when I tried with pyhydroquebec -u MYACCOUNT -p MYPASSWORD :
`Task exception was never retrieved
future: <Task finished coro=<HydroQuebecClient.fetch_data() done, defined at /home/pi/.local/lib/python3.5/site-packages/pyhydroquebec/client.py:388> exception=TypeError('Invalid variable type: mapping value should be str or int, got None',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/.local/lib/python3.5/site-packages/pyhydroquebec/client.py", line 431, in fetch_data
    daily_data = yield from self._get_daily_data(p_p_id, start_date, end_date)
  File "/home/pi/.local/lib/python3.5/site-packages/pyhydroquebec/client.py", line 276, in _get_daily_data
    timeout=self._timeout)
  File "/home/pi/.local/lib/python3.5/site-packages/aiohttp/client.py", line 361, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/home/pi/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 207, in __init__
    url2 = url.with_query(params)
  File "/home/pi/.local/lib/python3.5/site-packages/yarl/__init__.py", line 857, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/yarl/__init__.py", line 825, in _get_str_query
    "should be str or int, got {!r}".format(v))
TypeError: Invalid variable type: mapping value should be str or int, got None`
whith my father account it's working....

**Comment by QcVictor** [comment]
Update: Don't ask my why, after big power outage (7h) everything is back to normal....

**Comment by ncareau** [comment]
Not sure if this was the case, but i had also a period where i wasn't able to access the API.
My though were that they probably limit the API if you call it too much in a period of time.
