### ISSUE TITLE
Connection failed due to SSL? 

### ISSUE THREAD

**Issue by josephrenda** [titilambert/pyhydroquebec#36]
aiohttp fails for me... why?

time is good. Certificate of hyrdroquebec.com is valid? 

  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 493, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyhydroquebec/client.py", line 77, in _get_login_page
    timeout=self._timeout)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 104, in __iter__
    ret = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 749, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 860, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 832, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 802, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host session.hydroquebec.com:443 ssl:True [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/pyhydroquebec/client.py", line 400, in fetch_data
    login_url = yield from self._get_login_page()
  File "/usr/local/lib/python3.5/dist-packages/pyhydroquebec/client.py", line 79, in _get_login_page
    raise PyHydroQuebecError("Can not connect to login page")
pyhydroquebec.client.PyHydroQuebecError: Can not connect to login page

**Comment by titilambert** [comment]
Duplicate from https://github.com/titilambert/pyhydroquebec/issues/35#issuecomment-540109757
