### ISSUE TITLE
Quick How to for docker

### ISSUE THREAD

**Issue by QcVictor** [titilambert/pyhydroquebec#45]
Hi Guys 
One of you could you help me to start with docker version, look like not as simple as type 👍 docker run -e PYHQ_USER=*** -e PYHQ_PASSWORD=*** registry.gitlab.com/ttblt-hass/pyhydroquebec/cli:master .....
Thanks in advance, Vic

**Comment by titilambert** [comment]
Could you give me the output of your command ?

**Comment by QcVictor** [comment]
when I run: docker run -e PYHQ_USER=*** -e PYHQ_PASSWORD=*** registry.gitlab.com/ttblt-hass/pyhydroquebec/cli:master, I can seen my data, but I don't no what to do for send it via json or mqtt !

**Comment by titilambert** [comment]
Ok, I just updated the readme: https://github.com/titilambert/pyhydroquebec#mqtt-daemon
Tell me if you get what you want

**Comment by QcVictor** [comment]
Where I have to apply this cmd ? I don't have user password for my broker..

**Comment by ioio85** [comment]
Hi I have been trying to make this work. Is the command below correct ? 

`sudo docker run -e PYHQ_USER=***  -e PYHQ_PASSWORD=*** -e PYHQ_CONTRACT=*** -e MQTT_USERNAME=*** -e MQTT_PASSWORD=*** -e MQTT_HOST=*** -e MQTT_PORT=*** -e CONFIG=config.yaml -e PYHQ_OUTPUT=MQTT registry.gitlab.com/ttblt-hass/pyhydroquebec:master`

what is the config.yaml exactly? Where is supposed to be located?

I am getting an error:
`2019-12-31 21:14:10,242 - INFO - mqtt-hydroquebec - Initializing...
Traceback (most recent call last):
  File "/usr/local/bin/mqtt_pyhydroquebec", line 11, in <module>
    load_entry_point('pyhydroquebec==3.0.0', 'console_scripts', 'mqtt_pyhydroquebec')()
  File "/usr/local/lib/python3.7/site-packages/pyhydroquebec-3.0.0-py3.7.egg/pyhydroquebec/__main__.py", line 174, in mqtt_daemon
  File "/usr/local/lib/python3.7/site-packages/pyhydroquebec-3.0.0-py3.7.egg/pyhydroquebec/mqtt_daemon.py", line 38, in __init__
  File "/usr/local/lib/python3.7/site-packages/mqtt_hass_base/__init__.py", line 26, in __init__
    self.read_config()
  File "/usr/local/lib/python3.7/site-packages/pyhydroquebec-3.0.0-py3.7.egg/pyhydroquebec/mqtt_daemon.py", line 42, in read_config
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
`

**Comment by titilambert** [comment]
You just forgot -v `pwd`/config.yaml:/config.yaml` and set `-e CONFIG=/config.yaml`
