### ISSUE TITLE
Could not get annual data

### ISSUE THREAD

**Issue by mdallaire** [titilambert/pyhydroquebec#5]
Hi,

I am having issues since HQ release the new format. The short error I get is the following :
[homeassistant.components.sensor.hydroquebec] Error on receive last Hydroquebec data: Could not get annual data

This contract was working properly previously. One thing that may be related is that this contract is new since the beginning of March 2017 so in the new HQ webpage I don't have access to any of the following features yet:

https://www.hydroquebec.com/portail/group/clientele/portrait-de-consommation
 - I don't have the "Comparer à l'an dernier" switch under "Vue d'ensemble - période en cours" and "Historique", it is grayed out.
![image](https://user-images.githubusercontent.com/23340663/33800741-9c948578-dd14-11e7-99d6-303cf60634db.png)

See below for the full log. I edited out the contract number.
```
Dec 08 13:14:05 ha hass[13925]: 2017-12-08 13:14:05 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.hydroquebec_yesterday_total_consumption is taking over 10 seconds
Dec 08 13:14:11 ha hass[13925]: 2017-12-08 13:14:11 ERROR (Thread-35) [homeassistant.components.sensor.hydroquebec] Error on receive last Hydroquebec data: Could not get annual data
Dec 08 13:14:11 ha hass[13925]: 2017-12-08 13:14:11 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydroquebec_yesterday_total_consumption fails
Dec 08 13:14:11 ha hass[13925]: Traceback (most recent call last):
Dec 08 13:14:11 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
Dec 08 13:14:11 ha hass[13925]:     yield from self.async_device_update()
Dec 08 13:14:11 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
Dec 08 13:14:11 ha hass[13925]:     yield from self.hass.async_add_job(self.update)
Dec 08 13:14:11 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Dec 08 13:14:11 ha hass[13925]:     yield self  # This tells Task to wait for completion.
Dec 08 13:14:11 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Dec 08 13:14:11 ha hass[13925]:     future.result()
Dec 08 13:14:11 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Dec 08 13:14:11 ha hass[13925]:     raise self._exception
Dec 08 13:14:11 ha hass[13925]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 08 13:14:11 ha hass[13925]:     result = self.fn(*self.args, **self.kwargs)
Dec 08 13:14:11 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 157, in update
Dec 08 13:14:11 ha hass[13925]:     self.hydroquebec_data.update()
Dec 08 13:14:11 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
Dec 08 13:14:11 ha hass[13925]:     result = method(*args, **kwargs)
Dec 08 13:14:11 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 192, in update
Dec 08 13:14:11 ha hass[13925]:     self.data = self.client.get_data(self._contract)[self._contract]
Dec 08 13:14:11 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 337, in get_data
Dec 08 13:14:11 ha hass[13925]:     raise PyHydroQuebecError("Contract {} not found".format(contract))
Dec 08 13:14:11 ha hass[13925]: pyhydroquebec.client.PyHydroQuebecError: Contract "Edited out" not found
Dec 08 13:14:19 ha hass[13925]: 2017-12-08 13:14:19 ERROR (Thread-42) [homeassistant.components.sensor.hydroquebec] Error on receive last Hydroquebec data: Could not get annual data
Dec 08 13:14:19 ha hass[13925]: 2017-12-08 13:14:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydroquebec_period_total_bill fails
Dec 08 13:14:19 ha hass[13925]: Traceback (most recent call last):
Dec 08 13:14:19 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
Dec 08 13:14:19 ha hass[13925]:     yield from self.async_device_update()
Dec 08 13:14:19 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
Dec 08 13:14:19 ha hass[13925]:     yield from self.hass.async_add_job(self.update)
Dec 08 13:14:19 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Dec 08 13:14:19 ha hass[13925]:     yield self  # This tells Task to wait for completion.
Dec 08 13:14:19 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Dec 08 13:14:19 ha hass[13925]:     future.result()
Dec 08 13:14:19 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Dec 08 13:14:19 ha hass[13925]:     raise self._exception
Dec 08 13:14:19 ha hass[13925]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 08 13:14:19 ha hass[13925]:     result = self.fn(*self.args, **self.kwargs)
Dec 08 13:14:19 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 157, in update
Dec 08 13:14:19 ha hass[13925]:     self.hydroquebec_data.update()
Dec 08 13:14:19 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
Dec 08 13:14:19 ha hass[13925]:     result = method(*args, **kwargs)
Dec 08 13:14:19 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 192, in update
Dec 08 13:14:19 ha hass[13925]:     self.data = self.client.get_data(self._contract)[self._contract]
Dec 08 13:14:19 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 337, in get_data
Dec 08 13:14:19 ha hass[13925]:     raise PyHydroQuebecError("Contract {} not found".format(contract))
Dec 08 13:14:19 ha hass[13925]: pyhydroquebec.client.PyHydroQuebecError: Contract "Edited out" not found
Dec 08 13:14:27 ha hass[13925]: 2017-12-08 13:14:27 ERROR (Thread-11) [homeassistant.components.sensor.hydroquebec] Error on receive last Hydroquebec data: Could not get annual data
Dec 08 13:14:27 ha hass[13925]: 2017-12-08 13:14:27 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydroquebec_period_mean_daily_consumption fails
Dec 08 13:14:27 ha hass[13925]: Traceback (most recent call last):
Dec 08 13:14:27 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
Dec 08 13:14:27 ha hass[13925]:     yield from self.async_device_update()
Dec 08 13:14:27 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
Dec 08 13:14:27 ha hass[13925]:     yield from self.hass.async_add_job(self.update)
Dec 08 13:14:27 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Dec 08 13:14:27 ha hass[13925]:     yield self  # This tells Task to wait for completion.
Dec 08 13:14:27 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Dec 08 13:14:27 ha hass[13925]:     future.result()
Dec 08 13:14:27 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Dec 08 13:14:27 ha hass[13925]:     raise self._exception
Dec 08 13:14:27 ha hass[13925]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 08 13:14:27 ha hass[13925]:     result = self.fn(*self.args, **self.kwargs)
Dec 08 13:14:27 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 157, in update
Dec 08 13:14:27 ha hass[13925]:     self.hydroquebec_data.update()
Dec 08 13:14:27 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
Dec 08 13:14:27 ha hass[13925]:     result = method(*args, **kwargs)
Dec 08 13:14:27 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 192, in update
Dec 08 13:14:27 ha hass[13925]:     self.data = self.client.get_data(self._contract)[self._contract]
Dec 08 13:14:27 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 337, in get_data
Dec 08 13:14:27 ha hass[13925]:     raise PyHydroQuebecError("Contract {} not found".format(contract))
Dec 08 13:14:27 ha hass[13925]: pyhydroquebec.client.PyHydroQuebecError: Contract "Edited out" not found
Dec 08 13:14:36 ha hass[13925]: 2017-12-08 13:14:36 ERROR (Thread-21) [homeassistant.components.sensor.hydroquebec] Error on receive last Hydroquebec data: Could not get annual data
Dec 08 13:14:36 ha hass[13925]: 2017-12-08 13:14:36 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydroquebec_balance fails
Dec 08 13:14:36 ha hass[13925]: Traceback (most recent call last):
Dec 08 13:14:36 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
Dec 08 13:14:36 ha hass[13925]:     yield from self.async_device_update()
Dec 08 13:14:36 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
Dec 08 13:14:36 ha hass[13925]:     yield from self.hass.async_add_job(self.update)
Dec 08 13:14:36 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Dec 08 13:14:36 ha hass[13925]:     yield self  # This tells Task to wait for completion.
Dec 08 13:14:36 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Dec 08 13:14:36 ha hass[13925]:     future.result()
Dec 08 13:14:36 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Dec 08 13:14:36 ha hass[13925]:     raise self._exception
Dec 08 13:14:36 ha hass[13925]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 08 13:14:36 ha hass[13925]:     result = self.fn(*self.args, **self.kwargs)
Dec 08 13:14:36 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 157, in update
Dec 08 13:14:36 ha hass[13925]:     self.hydroquebec_data.update()
Dec 08 13:14:36 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
Dec 08 13:14:36 ha hass[13925]:     result = method(*args, **kwargs)
Dec 08 13:14:36 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 192, in update
Dec 08 13:14:36 ha hass[13925]:     self.data = self.client.get_data(self._contract)[self._contract]
Dec 08 13:14:36 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 337, in get_data
Dec 08 13:14:36 ha hass[13925]:     raise PyHydroQuebecError("Contract {} not found".format(contract))
Dec 08 13:14:36 ha hass[13925]: pyhydroquebec.client.PyHydroQuebecError: Contract "Edited out" not found
Dec 08 13:14:44 ha hass[13925]: 2017-12-08 13:14:44 ERROR (Thread-10) [homeassistant.components.sensor.hydroquebec] Error on receive last Hydroquebec data: Could not get annual data
Dec 08 13:14:44 ha hass[13925]: 2017-12-08 13:14:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydroquebec_period_mean_daily_bill fails
Dec 08 13:14:44 ha hass[13925]: Traceback (most recent call last):
Dec 08 13:14:44 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
Dec 08 13:14:44 ha hass[13925]:     yield from self.async_device_update()
Dec 08 13:14:44 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
Dec 08 13:14:44 ha hass[13925]:     yield from self.hass.async_add_job(self.update)
Dec 08 13:14:44 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Dec 08 13:14:44 ha hass[13925]:     yield self  # This tells Task to wait for completion.
Dec 08 13:14:44 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Dec 08 13:14:44 ha hass[13925]:     future.result()
Dec 08 13:14:44 ha hass[13925]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Dec 08 13:14:44 ha hass[13925]:     raise self._exception
Dec 08 13:14:44 ha hass[13925]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 08 13:14:44 ha hass[13925]:     result = self.fn(*self.args, **self.kwargs)
Dec 08 13:14:44 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 157, in update
Dec 08 13:14:44 ha hass[13925]:     self.hydroquebec_data.update()
Dec 08 13:14:44 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
Dec 08 13:14:44 ha hass[13925]:     result = method(*args, **kwargs)
Dec 08 13:14:44 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/hydroquebec.py", line 192, in update
Dec 08 13:14:44 ha hass[13925]:     self.data = self.client.get_data(self._contract)[self._contract]
Dec 08 13:14:44 ha hass[13925]:   File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 337, in get_data
Dec 08 13:14:44 ha hass[13925]:     raise PyHydroQuebecError("Contract {} not found".format(contract))
Dec 08 13:14:44 ha hass[13925]: pyhydroquebec.client.PyHydroQuebecError: Contract "Edited out" not found
```

**Comment by titilambert** [comment]
Hello, Thanks for reporting.

Which version are you using ?

**Comment by mdallaire** [comment]
Home Assistant 0.59.2
-- 
Envoyé d'un appareil mobile / Sent from a mobile device

**Comment by titilambert** [comment]
I'm preparing a new version of the component, this will be fixed in this new version

**Comment by titilambert** [comment]
See here: https://github.com/home-assistant/home-assistant/pull/10795

**Comment by mdallaire** [comment]
Great! Thank you for your work on this component 👍

**Comment by titilambert** [comment]
Should be resolved here: https://github.com/home-assistant/home-assistant/pull/10795
