### ISSUE TITLE
can't connect to login page

### ISSUE THREAD

**Issue by C0rpc** [titilambert/pyhydroquebec#52]
Hi

i installed pyhydroquebec but when I use "pyhydroquebec -uUSERNAME -p PASSWORD", I get an error. I could not find anything that would help me fix this in the README file. 

Here is my error:

`Task exception was never retrieved
future: <Task finished name='Task-2' coro=<HydroQuebecClient.fetch_data() done, defined at c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py:394> exception=PyHydroQuebecError('Can not connect to login page')>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 1046, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 1076, in _create_connection_transport
    await waiter
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py", line 76, in _get_login_page
    raw_res = yield from self._session.get(HOME_URL,
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp\connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.hydroquebec.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py", line 400, in fetch_data
    login_url = yield from self._get_login_page()
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py", line 79, in _get_login_page
    raise PyHydroQuebecError("Can not connect to login page")
pyhydroquebec.client.PyHydroQuebecError: Can not connect to login page`

**Comment by bullmoose20** [comment]
Hello, 
I am getting the following error as well. 
I tried both pyhydroquebec -u USERNAME -p PASSWORD and pyhydroquebec -u USERNAME@hotmail.com -p PASSWORD
and both give me the same results.

Task exception was never retrieved
future: <Task finished coro=<HydroQuebecClient.fetch_data() done, defined at /usr/local/lib/python3.7/site-packages/pyhydroquebec/client.py:394> exception=PyHydroQuebecError('Can not connect to login page')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 985, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1013, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyhydroquebec/client.py", line 77, in _get_login_page
    timeout=self._timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 939, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host session.hydroquebec.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyhydroquebec/client.py", line 400, in fetch_data
    login_url = yield from self._get_login_page()
  File "/usr/local/lib/python3.7/site-packages/pyhydroquebec/client.py", line 79, in _get_login_page
    raise PyHydroQuebecError("Can not connect to login page")
pyhydroquebec.client.PyHydroQuebecError: Can not connect to login page

**Comment by starwolf73** [comment]
I have the same error. Is the latest change to fix HQ new web site is replicated to the python repository when we use "pip install? Or we need to install manually from github to get the latest fixed? If so it is possible to provide a little more info (or link) on how to install manually, as I can't find so far any instruction on how to build it from your repository. Thanks

**Comment by starwolf73** [comment]
I found out that the version of pyhydroquebec I was using from the PIP repository is 2.4.0 which doesn't seem to work. To show the version use:
`pyhydroquebec -V`

If you need to install manually the version 3.0.0 on Windows, here so far what work for me:
- Download the latest change from github repositoy using the green button "Clone or download"
- Click on "Download ZIP"
- Unzip into a location
- Start Windows Command Prompt (cmd) and go to the location you unzip the file.

We can't use the MakeFile on windows as it using a unix command 'which'. So we need to build it manually. (FYI "make" on Windows required to be install `pip install py-make` and you can run with `pymake`)

I look at the Makefile and run the following:
py -m venv pyhq
pyhq\scripts\activate
pyhq\scripts\pip install -r requirements.txt
pyhq\scripts\pip install -r test_requirements.txt
pyhq\scripts\python setup.py develop

pyhydroquebec -V -> V3.0.0

**Comment by bullmoose20** [comment]
Any ideas on what the steps would be in hassio/homeassistant/unix?

I have version 2.4.0 installed and have no idea why 3.0.0 has not been promoted so that i can perform a simple "pip install pyhydroquebec" command.

**Comment by C0rpc** [comment]
thanks Starwolf

I've been able to install V3.0.0 following your isntructions, however I still get an error when trying 

pyhydroquebec -u -p

I get 
```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<HydroQuebecClient.fetch_data() done, defined at c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py:394> exception=PyHydroQuebecError('No login form find')>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py", line 400, in fetch_data
    login_url = yield from self._get_login_page()
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pyhydroquebec\client.py", line 85, in _get_login_page
    raise PyHydroQuebecError("No login form find")
pyhydroquebec.client.PyHydroQuebecError: No login form find
```

**Comment by llluis** [comment]
> Any ideas on what the steps would be in hassio/homeassistant/unix?

https://github.com/titilambert/pyhydroquebec/issues/49

**Comment by titilambert** [comment]
I just push v3.0.5.
You can now install pyhydroquebec with `pip install pyhydroquebec==3.0.5` or just `pip install pyhydroquebec --upgrade` if it's already installed
