### ISSUE TITLE
Contract xxxx not found with home-assistant

### ISSUE THREAD

**Issue by aarnaud** [titilambert/pyhydroquebec#7]
All information are Good (contract, password...), i try with different version of pyhydroquebec. Last version tried : 2.1.0

But if i try directly hydroquebec it's work

````
2018-01-05 09:32:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydroquebec_period_total_consumption fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/sensor/hydroquebec.py", line 157, in update
    self.hydroquebec_data.update()
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/sensor/hydroquebec.py", line 192, in update
    self.data = self.client.get_data(self._contract)[self._contract]
  File "/opt/home-assistant/deps/lib/python3.5/site-packages/pyhydroquebec/client.py", line 350, in get_data
    raise PyHydroQuebecError("Contract {} not found".format(contract))
````

**Comment by titilambert** [comment]
Hello, This is really strange :/ If I understand well,
```
pyhydroquebec -u USERNAME -p PASSWORD -c CONTRACTID 
```
is working, but not on home assistant ?!

**Comment by aarnaud** [comment]
Fixed after upgrade home assistant
